"""add_library_actions

Revision ID: 1dcc21e11f9c
Revises: 913d83e7e8f3
Create Date: 2026-05-13 03:12:31.512832

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '1dcc21e11f9c'
down_revision: Union[str, None] = '913d83e7e8f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('library_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('torrent_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['torrent_id'], ['library_torrents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('library_actions')
    # ### end Alembic commands ###
