"""add ingest checkpoints

Revision ID: 3f39ac11a6d7
Revises: 20260516b
Create Date: 2026-05-15 21:32:10.275643

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '3f39ac11a6d7'
down_revision: Union[str, None] = '20260516b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingest_checkpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingest_checkpoints')
    # ### end Alembic commands ###
