"""library_revamp

Revision ID: 913d83e7e8f3
Revises: 0001
Create Date: 2026-05-13 02:18:49.407969

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '913d83e7e8f3'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('library_bulk_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('performer_or_studio', sa.String(length=255), nullable=False),
    sa.Column('query_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('total_found', sa.Integer(), nullable=True),
    sa.Column('sent_to_torbox', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('library_torrents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('info_hash', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('performer_name', sa.String(length=255), nullable=True),
    sa.Column('studio_name', sa.String(length=255), nullable=True),
    sa.Column('quality', sa.String(length=50), nullable=True),
    sa.Column('size', sa.String(length=50), nullable=True),
    sa.Column('seeders', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('magnet', sa.Text(), nullable=True),
    sa.Column('torrent_url', sa.Text(), nullable=True),
    sa.Column('is_megapack', sa.Boolean(), nullable=True),
    sa.Column('is_cached_torbox', sa.Boolean(), nullable=True),
    sa.Column('is_local_stash', sa.Boolean(), nullable=True),
    sa.Column('local_stash_path', sa.Text(), nullable=True),
    sa.Column('torbox_id', sa.String(length=255), nullable=True),
    sa.Column('added_to_torbox_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('info_hash')
    )
    op.create_table('stashdb_cache_performers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stashdb_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('aliases', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('scene_count', sa.Integer(), nullable=True),
    sa.Column('career_years', sa.String(length=100), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stashdb_id')
    )
    op.create_table('stashdb_cache_studios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stashdb_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('scene_count', sa.Integer(), nullable=True),
    sa.Column('parent_studio', sa.String(length=255), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stashdb_id')
    )
    op.create_table('library_torrent_previews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('torrent_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['torrent_id'], ['library_torrents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('library_torrent_previews')
    op.drop_table('stashdb_cache_studios')
    op.drop_table('stashdb_cache_performers')
    op.drop_table('library_torrents')
    op.drop_table('library_bulk_jobs')
    # ### end Alembic commands ###
